# Generated by Django 5.2.7 on 2025-10-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FX',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factor.base')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fx_from_currency', to='factor.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fx_to_currency', to='factor.currency')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('factor.base',),
        ),
        migrations.CreateModel(
            name='Volatility',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='factor.base')),
                ('base_factor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='volatility_factor', to='factor.base')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('factor.base',),
        ),
    ]
